feat: add page component radio
Leaf-Pallete/leaf-pallete pull request #126
Opened 2024-09-25 14:47 UTC by EnzoHessel

add page component radio

2024-09-25 23:56 UTC, AmodeusR commented
Faltou configurar o botão card na página components-module do Radio para redirecionar à página Radio

2024-09-26 00:06 UTC, DouglasBsales requested changes

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-best-practices.tsx
> +				{images.slice(0, 2).map((image) => (
Crie um array específico para cada " parte " do código com por exemplo: 

title: best Practices,
description: text que será utilizado,
imgLight: diretório da imagem,
imgDark: diretório da imagem,

Assim você tem mais controle do que está sendo renderizado invés do modo slice que nos da a impressão de uma informação " solta " no código.

em relação as imagens você irá utilizar o método passado

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-hero.tsx
> +			<RadioHeroFallback />
Nao utilizaremos mais do FallbackComponent. 

O uso de fallback com o skeleton nos trás muitas necessidades de criarmos vários components para termos um único resultado. 

![alt text](image.png)

O novo método utilizado será esse. 

Basicamente temos duas imagens que carregam duas fotos, uma light e uma dark. 

conforme a class dark for aplicada a imagem light toma um hidden e a imagem dark um block. 

dessa forma sanamos o problema sem o uso de mais components adicionais

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-anatomy.tsx
> +			<RadioAnatomyFallback />
remover os componentsFallBack e utilizar o novo formato

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-hero.tsx
> +			<RadioHeroFallback />
![image](https://github.com/user-attachments/assets/87712dd6-72b5-44f0-b4e1-d0fc5e68c63e)

Método a ser utilizado

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-hero.tsx
> +		return resolvedTheme === "dark" ? darkSrc : lightSrc;
Nao utilizaremos mais desse formato com useClient e o resolvedTheme com condicional renderizando dark e light

Utilizaremos duas imagens com modificação apenas nas classes como na imagem mostrada no comentário explicativo sobre o método

2024-09-26 00:06 UTC, DouglasBsales commented on components/components-module/radio/radio-best-practices.tsx
> +const RadioBestPracticesFallback = ({
Remover os components fallBack e utilizar do novo formato

2024-09-26 00:35 UTC, AmodeusR requested changes
Eis aqui alguns dos problemas que percebi. Peço ajuda dos outros revisores para revisar minha revisão porque essa é a primeira revisão de código que faço kkk E claro, para o dono da PR, sinta-se livre para contrapor-se às coisas que eu disse, já que eu posso ter cometido algum engano no que levantei.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-hero.tsx
> +				that has only two states: selected (activated) or not selected
[Desktop]
No design figma, o tamanho da fonte está Fonts/Paragraph/P2 (20px), e não 18px como é o caso aqui.

[Mobile]
Por algum motivo, em contraste com todo o resto da página, na versão mobile o tamanho de fonte usado no texto da Hero Section é Fonts/Paragraph/P3 (16px). Isso cria uma irregularidade, não sei foi intencional, então seria bom contatar os responsáveis pelo design.

Outro detalhe, o tamanho do h1 é 40px no Mobile, e não 36px.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-hero.tsx
> +			width={1047}
É bom fazer uma melhor descrição (alt) da imagem, algo como "Radio Hero image showing some radio inputs". Alt's devem ser sempre descritivas, lembre-se que elas servem para quem estiver usando leitores de tela e geralmente são pessoas que possuem deficiência visual e não podem ver bem.

 Em caso de a imagem ser apenas um adereço à página – como no caso de ícones –, não se deve utilizar uma alt.

Vou deixar à sua consideração se essa imagem da Hero Section é apenas um adereço ou não e fazer a mudança de acordo.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-use-cases.tsx
> +				interfaces (UI) and digital forms. They are used when the user needs to
[Desktop]
Aqui também o tamanho da fonte está Fonts/Paragraph/P2 (20px), e não 18px

[Mobile]
Algo parecido com o Hero acontece aqui, a diferença é que o usado no seu código é o tamanho da fonte de 16px, enquanto no design está 20px. É bom contatar os responsáveis pelo design para saber a intenção deles aqui e resolver esse conflito de código/design.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-use-cases.tsx
> +								{useCase.id} - {useCase.text}:
O font-weight no design dos cabeçalhos dos pontos é semibold e não bold.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-use-cases.tsx
> +				situation where it's necessary to ensure that only one option is
Aqui também o tamanho da fonte está Fonts/Paragraph/P2 (20px), e não 18px.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-anatomy.tsx
> +				</li>
O espaço entre estes itens está maior no código no que no design. Não sei dizer exatamente a diferença de espaço entre eles no design já que foram feitos como um bloco de texto separados apenas pelo seu line-height (de 150%). Se alguém puder ajudar a dizer o valor exato, eu agradeceria, mas me parece que um gap-1 ou nenhum gap é o mais próximo do que está no design.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-best-practices.tsx
> +			</p>
Outro caso em que no design está 20px e não 18px. Inclusive no seu código na versão Mobile o tamanho da fonte é reduzido para 16px, porém no design o tamanho é mantido em 20px a todo momento.

2024-09-26 00:35 UTC, AmodeusR commented on components/components-module/radio/radio-best-practices.tsx
> +				</li>
Aqui o tamanho da fonte está 16px até mesmo na versão Desktop. No design o tamanho é 20px ambos Desktop e Mobile.

2024-09-26 12:17 UTC, cardrocha commented on components/components-module/radio/radio-use-cases.tsx
> +}
Não há muito a acrescentar. Porém, gostaria de fazer algumas sugestões fique à vontade para considerá-las.

Temos uma pasta "types" onde ficam os tipos utilizados no projeto. Seria interessante mover a interface UseCase para lá e então exportá-la, pois deixa o código mais limpo. 

Fica a sugestão remover do componente.

2024-09-26 12:17 UTC, cardrocha commented on components/components-module/radio/radio-use-cases.tsx
> +];
Da mesma forma, sugiro mover o array "useCases" para a pasta "config" e exportá-lo de lá. Assim, no componente você apenas importaria o array e a interface que estaria em "types"

Como disse antes, apenas uma sugestão, não é regra. Mas acho válido para deixar código mais limpo.

2024-09-26 12:30 UTC, cardrocha commented on components/components-module/radio/radio-best-practices.tsx
> +}
Aqui mesmo caso de "UseCase", poderia mover a interface 'ImageProps" para pasta "types".

2024-09-26 12:31 UTC, cardrocha commented on components/components-module/radio/radio-best-practices.tsx
> +];
Assim como Array "images", poderia mover  para pasta "config".

2024-09-27 15:45 UTC, AmodeusR commented on components/components-module/radio/radio-hero.tsx
> +			width={1047}
Opa, pequeno engano da minha parte: caso a imagem seja apenas ilustrativa, **o alt deve ficar vazio.** Então ficaria apenas alt="". Em qualquer ocasião o alt deve existir.

2024-10-03 02:39 UTC, AmodeusR approved these changes

2024-10-03 23:35 UTC, merged