PR opened to implement the task: Corrigir o alinhamento da fonte no front end
Leaf-Pallete/leaf-pallete pull request #39
Opened 2024-08-04 19:54 UTC by cardrocha

Eu e João decidimos usar a propriedade do Tailwind diretamente nos estilos globais que envolvem toda a aplicação.
A propriedade tem finalidade de aplica alinhamento e altura a dígitos numéricos na fonte.
 
![lining-global](https://github.com/user-attachments/assets/3b471d60-ff42-45bd-bf56-3f2319a8fddb)

**Antes:**
![antes](https://github.com/user-attachments/assets/3ff12c25-3f9e-465a-b61c-bc058e92222b)

**Depois:**
![depois](https://github.com/user-attachments/assets/d4c3e3a0-06a2-43de-a6bb-842b4b3ccaf3)

Era possível também aplicar diretamente no componente. Qual teria mesmo resultado... aplicando a propriedade a toda aplicação.
![lining-layout](https://github.com/user-attachments/assets/96c1fd62-e079-4988-8b4a-a98e3bf39e34)

2024-08-06 18:47 UTC, pedrodecf requested changes
O ponto principal é desacoplar o `Sidebar` do `Header`, e depois adicionar ambos no `layout.tsx`.

Não cheguei a fazer as requisições de mudanças, mas notei muitas inconsistências visual em relação ao protótipo (tamanho de fonte, espaçamento, cores, bordas e etc), será necessário um review mais aprofundado para fazer o levantamento.

Antes de aprovar, preciso alinhar com o time de UX/UI algumas coisas.

2024-08-06 18:47 UTC, pedrodecf commented on components/header.tsx
> +			<Sidebar />
O Componente `<Sidebabar />` não deve compor o `<Header />`, ele precisa ser implementando no `layout.tsx`

2024-08-07 20:28 UTC, cardrocha commented on app/dashboard/page.tsx
Fiz a implementação no layout.tsx
![layout2](https://github.com/user-attachments/assets/171274e5-34ca-490f-8b9f-22e3380d6326)
No page.tsx fica a tela inicial de anúncio do desenvolvimento do projeto, por isso inicialmente não coloquei nela. Mas ajustei a tela inicial entre header e o sidebar.
![layout](https://github.com/user-attachments/assets/f6602776-de72-41bf-aa37-943c6944f0ba)
Quebrou o layout do mobile, mas já arrumei.
![layout3](https://github.com/user-attachments/assets/54952468-634c-4d64-b973-0f9ca1f9187c)

2024-08-07 20:31 UTC, cardrocha commented on app/item1/page.tsx
Essa tela não existe no figma, ela apenas exemplifica como implementar links de cada item.
![pageItem2](https://github.com/user-attachments/assets/2d1c3da2-c68d-4a88-83b5-3ac8eca4cabb)
![pageItem](https://github.com/user-attachments/assets/fbca7998-15d2-4924-9976-1fef0005e4b5)

2024-08-07 20:33 UTC, cardrocha commented on app/page.tsx
Retirei, não lembro se usei antes dessas mudanças algum hook do react. Por isso o uso dele... de qualquer forma obrigado por avisar. Pois nem tinha reparado.

2024-08-07 20:35 UTC, cardrocha commented on components/header.tsx
> +				<label htmlFor="placeholder">
Implementado! Outro detalhe que não me atentei, pois se usei Input do shadcn, por que não o label.
Valeu!

2024-08-07 20:55 UTC, cardrocha commented on components/header.tsx
Então no meu curso nos passou a usar sempre arrow function nos components do react. Mas já mudei de todos componentes, e futuramente usarei o function.
![header](https://github.com/user-attachments/assets/fd1d27b2-d733-4360-a1c6-e8bc993ce2ff)
![sidebar](https://github.com/user-attachments/assets/2e7d16fa-06af-4d35-a87d-be5b9d5d5633)
![item1](https://github.com/user-attachments/assets/bc57646a-6b1f-4fa9-999a-e49671798e51)

2024-08-07 21:07 UTC, cardrocha commented on components/siderBar.tsx
> +import * as D from "@/components/ui/dropdown-menu";
Então não tem mais aquele figma, mas acredito que espaçamento era de 24px, foi que usei.

![sidebarMenu](https://github.com/user-attachments/assets/9f765035-2891-4676-ad1e-20e079bf2383)

Eu usei dropdown que era único que achei parecido com layout, poderia usar outro component do shadcn se achar necessário. Eu modifiquei bastante o layout para se adaptar ao design do figma.

Poderia faz por div, escondendo ao clicar usando trasnlation-y-0 | translate-y-full ao tamanho da div do links.

Enfim aceito sugestões.

2024-08-07 21:09 UTC, cardrocha commented on components/siderBar.tsx
> +										className="flex text-secondary-foreground font-semibold pl-4 outline-none pr-[1px] w-[216px] justify-between"
Sim, como mencionei faço isso para adaptar o layout, neste component mesmo se não chumbo essas valores, o layout fica desalinhado. Mas posso dar uma olhada.

2024-08-07 21:11 UTC, cardrocha commented on components/siderBar.tsx
> +						className="flex flex-col justify-between bg-orange-100 dark:bg-card"
Esse bg-orange-100, e questão da cor utilizada no figma que estava um valor definido pelo autor. Talvez por falta de comunicação entre eu o Ux, não decidimos um valor das cores do tailwind css.

2024-08-07 21:12 UTC, cardrocha commented on components/header.tsx
> +			<Sidebar />
Sim, já ajustado.

2024-08-07 22:10 UTC, cardrocha commented on components/siderBar.tsx
Pronto, quebrei o componente o sidebar  em dois a versão desktop e mobile.
![sidebaritems](https://github.com/user-attachments/assets/8e3c62d1-623e-405a-be54-0bee9d4574ee)

2024-08-21 00:58 UTC, salviotonon approved these changes

2024-08-21 13:38 UTC, merged

2024-08-21 13:38 UTC, DouglasBsales commented
Task Corrigir alinhamento da fonte no front-end do ricardo mergeada