Feat card styles modules
Leaf-Pallete/leaf-pallete pull request #54
Opened 2024-08-19 14:25 UTC by DouglasBsales

Realizei o primeiro card da task que é o card-styles-modules. Não utilizei o motion pois ficou mais prático gerenciar tudo com um state com valor booleano para melhor controle das animações. Está configurado desktop e mobile

2024-08-19 17:14 UTC, salviotonon requested changes

2024-08-19 17:14 UTC, salviotonon commented on components/Home/CardDesignStyles/CardDesignStyles.tsx
> +							href="#"
aqui vamos padronizar os buttons com a função auxiliar "buttonVariants"

não precisamos se preoucupar em estilizar elementos clicaveis, deixamos mais ou menos assim

className={cn(buttonVariants({ size: "sm" }))}

nesse caso não precisamos do paragrafo interno

as medidas no figma vão ser alteradas para o formato padrão de buttons, o style guide ainda nao esta pronto, la no figma esta errado mesmo

2024-08-19 17:14 UTC, salviotonon commented on components/Home/CardDesignStyles/CardDesignStyles.tsx
> +							<FigmaLogoIcon className="w-6 h-6 text-primary" />
Estou pensando em omitir esse icone na tela de mobile para ter espaço para as dimensões do button, oque acha?

2024-08-19 17:14 UTC, salviotonon commented on components/Home/CardDesignStyles/CardDesignStyles.tsx
> +				<div className="w-[284px] h-[265px] sm:w-[503px] sm:h-[408px] flex flex-col bg-white rounded-t-xl border-t-2 border-r-2 border-l-2 border-[#E4E4E7]">
precisamos retirar as cores hard code e colocar as respectivas cores do nosso tema utilizada no global.css
Se não tiver corretamente setado la no figma, pode sinalizar com comentarios la no projeto para a equipe ajustar


você pode testar o dark mode, entrando no local storage do navegador, setando o thema de 'light" para "dark" e ai da um F5

2024-08-23 17:32 UTC, DouglasBsales commented
Removido o icon no mobile e removido as cores no hard-core. adicionado a imagem conforme o figma

2024-08-24 10:42 UTC, salviotonon approved these changes

2024-08-24 10:42 UTC, merged