PR opened to implement the task: desenvolver footer da home page.
Leaf-Pallete/leaf-pallete pull request #59
Opened 2024-08-22 16:35 UTC by cardrocha

Implementado o footer da Homepage, seguindo layout do figma. Já desenvolvido o design responsivo para versão mobile.,

![footer-section-4k](https://github.com/user-attachments/assets/899bdf8b-c1ae-4c71-bbf2-264e82a8fe00)

2024-08-22 17:43 UTC, DouglasBsales requested changes

2024-08-22 17:43 UTC, DouglasBsales commented on components/shared/Footer.tsx
> +		<section className="mb-8 bg-muted">
Remover o mb-8 nessa div que nao é necessário e aplicar um w-full nela, pois essa div engloba todo o conteúdo do footer, e ela precisa ser de um tamanho a nível inteiro da tela, o conteúdo de dentro que precisa ter o max-w

2024-08-22 17:43 UTC, DouglasBsales commented on components/shared/Footer.tsx
> +			<div className="flex flex-col md:flex-row gap-6 items-start justify-between py-10 px-6 md:py-20 md:px-28 w-full md:max-w-[1440px] mx-auto">
Pode remover o w-full dessa div de dentro, pois ela ja está ajustada com o max-w e o mx-auto

2024-08-22 17:43 UTC, DouglasBsales commented on components/shared/Footer.tsx
> +						<h1 className="text-base text-foreground">Leaf Pallete</h1>
Quando utilizamos links dessa forma com um texto dentro apenas, nao é necessário utilizar um parágrafo dentro dele, podemos escrever o texto diretamente e aplicar o className com o style diretamente na tag do link. text-base nao é necessário utilizar pois o padrão na web é esse mesmo de 16px. 

remover o h1 do link e passar o text-foreground para o className do Link

2024-08-22 17:43 UTC, DouglasBsales commented on components/shared/Footer.tsx
> +						</Link>
Remover os parágrafos dentro do link e aplicar o style diretamente no className do link

2024-08-22 17:43 UTC, DouglasBsales commented on components/shared/Footer.tsx
> +							</Link>
Remover os parágrafos dentro do link e aplicar o style diretamente no className do link

2024-08-22 20:38 UTC, DouglasBsales requested changes

2024-08-22 21:19 UTC, DouglasBsales approved these changes

2024-08-23 00:56 UTC, salviotonon requested changes
Ricardo consegue mandar nessa PR so o component footer? valeu

2024-08-24 10:43 UTC, salviotonon approved these changes

2024-08-24 10:43 UTC, merged