Create home page
Leaf-Pallete/leaf-pallete pull request #84
Opened 2024-09-01 14:05 UTC by AmodeusR

Não sei se consegui ser fiel ao design do Figma em alguns aspectos, então se possível gostaria de um feedback rígido quanto a esse aspecto. Ademais, eu tive que adicionar novos estilos a diferentes componentes da home para poder dar os devidos espaçamentos pois estavam um em cima do outro.

 Também não tinha certeza de como definir o tamanho máximo do container para o mobile, então eu fiz meio que um "olhômetro", deixando um max-width de 90%. Se isso for considerado não ideal, como eu deveria fazê-lo? Não consegui pensar de outra forma melhor até o momento.

Algumas observações gerais quanto ao resultado final:

- Os cards UI Components e Design Styles não ocupa todo o espaço da div pai no mobile
- A imagem do UI Components está quebrada
- Por eles terem um tamanho fixo eles quebram o site por volta dos 340px (largura)
- Os cards em Resources também quebram nesse tamanho por terem um tamanho mínimo de 340px
- Os cards de Last Updates estão sem imagens apropriadas
- O Header está na página home, apesar de que deveria estar no layout. Como já estava na página home, eu deixei aí

2024-09-01 16:45 UTC, DouglasBsales requested changes

2024-09-01 16:45 UTC, DouglasBsales commented on app/page.tsx
> +			<main className="py-20 max-w-[90%] mx-auto">
Em relação ao tamanho do container no mobile, voce coloca um w-full e o px que está setado no figma que é de 25px 
o px irá aplicar os paddings nas duas laterais, esquerda e direita. dessa forma você mantém todo conteúdo com w-full e apenas os paddings aplicados

2024-09-01 16:45 UTC, DouglasBsales commented on app/page.tsx
> +				<Resources />
Para mantem esses cards na posição correta em relação ao container pai você adiciona uma div envolvendo os dois components, o <LastUpdates /> e o <Resources/>

	<div className="flex flex-col items-center"> CARDS AQUI DENTRO</div>

2024-09-01 16:45 UTC, DouglasBsales commented on components/Home/hero-section/Hero.tsx
> +				className="max-w-[375px] md:max-w-[1440px] mx-auto mb-8 pt-24"
esse padding é p-20 que são 80pixels

2024-09-01 16:45 UTC, DouglasBsales commented on components/home/resources.tsx
> +		<section className="pt-20 w-full max-w-screen-xl mx-auto">
pode remover esse mx-auto

2024-09-01 16:45 UTC, DouglasBsales commented on components/home/last-updates.tsx
> +		<section className="pt-20 w-full max-w-screen-xl mx-auto">
pode remover esse mx-auto

2024-09-01 16:50 UTC, DouglasBsales commented
Comentário geral sobre os problemas: 

( Os cards UI Components e Design Styles não ocupa todo o espaço da div pai no mobile )

Precisamos alterar a construção dos dois cards para se adaptar ao tamanho da tela no mobile

Em relação aos cards quebrarem em 340 pixels creio que nao exista uma tela que chegue nessas proporções para que venha realmente existir um problema real em relação a isso.

Os cards de Last Updates estão sem imagens apropriadas

Precisamos alterar a construção dos cards para que a imagem ocupe todo tamanho do card 

O Component <Header/> veremos e mandaremos ele para o layout

2024-09-06 13:15 UTC, AmodeusR commented on app/page.tsx
> +			<main className="py-20 max-w-[90%] mx-auto">
O tamanho em questão aqui referente a versão desktop está ok? Só preciso adicionar o tamanho específico para o mobile?

2024-09-06 21:58 UTC, AmodeusR commented on components/Home/hero-section/Hero.tsx
> +				className="max-w-[375px] md:max-w-[1440px] mx-auto mb-8 pt-24"
De acordo com o design, tirando uma medição na mão aqui, o tamanho é de 94 de distância entre o título da página e o header, e o valor que chega mais próximo disso é o pt-24
![image](https://github.com/user-attachments/assets/af4615b3-254d-4642-94c6-4b0bb5d970c7)

2024-09-06 22:05 UTC, AmodeusR commented on app/page.tsx
> +				<Resources />
Refere-se às sessões LastUpdates e Resources? Usar flex para centralizar na página em vez de mx-auto?

2024-09-06 22:09 UTC, AmodeusR commented
O Tonon falou comigo sobre cuidar dos dois grandes cards para o mobile, então vou fazer as mudanças necessárias para esses dois cards ficarem certinhos na versão mobile. As imagens também vou ver de atualizar para imagens PNG de fundo transparente ao menos temporariamente, até que se decida o que fazer quanto a usar ou não múltiplas imagens de acordo com o tema da página.

 Obrigado pelo esclarecimento dos pontos levantados.

2024-09-07 02:06 UTC, DouglasBsales commented on app/page.tsx
> +			<main className="py-20 max-w-[90%] mx-auto">
O tamanho referente ao desktop está ok, você vai fazer o seguinte: 

![PR amodeus](https://github.com/user-attachments/assets/d7a5e8c3-6213-4f4f-a32d-8a95fcdc23b3)

segue esse exemplo na foto, linha 11 adiciona essa div 
e na main adiciona essas classes do tailwind que vai ficar tudo ok no mobile

2024-09-07 02:15 UTC, DouglasBsales commented on components/Home/hero-section/Hero.tsx
> +				className="max-w-[375px] md:max-w-[1440px] mx-auto mb-8 pt-24"
![image](https://github.com/user-attachments/assets/2deb9d43-5500-4be8-b422-7abc26703b30)

rapaz ta 80px mesmo

2024-09-07 22:55 UTC, AmodeusR commented
Último commit fiz a resolução dos pontos levantados, porém ainda falta a imagem quebrada do Card UI Component e adaptar para a versão Tablet tanto esses cards como realinhar os cards da sessão Last Updates para ficar 2 colunas.

2024-09-09 16:51 UTC, merged